#!/usr/bin/python
import argparse
from model import *

# Parse command line arguments
# ddctl.py -s <specfile.json> [--include-init] [--ectl-only] [--output <outputfile>]

argparser = argparse.ArgumentParser(description='Parse a CTL formula')
argparser.add_argument('-s', '--specfile', help='specfile.json', required=True)
argparser.add_argument('-e', '--ectl-only', help='only convert to ECTL', action='store_true')
argparser.add_argument('-o', '--output', help='output file name')
args = argparser.parse_args()

m = Model(specfile=args.specfile, ectl_only=args.ectl_only, output=args.output)

print("\n", m.ectlrepr, end=', ')
print(m.check())

